# Spring Boot Configuration
server.port=${PORT:8080}
spring.main.banner-mode=off

# MCP Server Configuration
spring.ai.mcp.server.stdio=true
spring.ai.mcp.server.name=weather-mcp-server
spring.ai.mcp.server.version=1.0.0

# Logging Configurations to prevent STDOUT pollution
logging.pattern.console=
logging.file.name=/Users/saran_j/Desktop/MCP_Server/MeteoBridge_Real-Time_Weather_Tool_for_LLM/mcp-server.log
logging.level.root=INFO
logging.level.org.springframework.ai=DEBUG

# OpenWeather API Configuration
openweather.api.key=${OPENWEATHER_API_KEY}
openweather.api.base-url=https://api.openweathermap.org/data/2.5
